#!/usr/bin/env bash
    chose=$(cat ~/.config/ssh/list.txt | fzf)
    echo $chose
    selected=$(echo $chose | awk '{print $1}')
    echo $selected
    name=$(echo $chose | awk '{print $3}')
    echo $name
selected_name=$(basename "$name" | tr . _)
#
# If not is select from FZF pop up, exit
if [[ -z $selected ]]; then
    exit 0
fi
    tmux new-session -ds $selected_name -c $selected ssh -Y $selected
    tmux switch-client -t $selected_name
