#!/usr/bin/env bash

options=$(cat ~/scripts/tmux/options/options_keys.txt | fzf)

option=$(echo $options | awk '{print $1}')



if [[ $option -lt 1 || $option -gt 2 ]]; then
  echo wrong option
else
  if [[ $option -eq 1 ]]; then
    cat ~/scripts/tmux/keys/tmux.txt | fzf
  fi
  if [[ $option -eq 2 ]]; then
    cat ~/scripts/tmux/keys/nvim.txt | fzf
  fi
fi


