#!/usr/bin/env bash

chose=$(cat $TMUXSCRIPTSDIR/ssh/list.txt| fzf)
selected=$(echo $chose | awk '{print $1}')
name=$(echo $chose | awk '{print $3}')
selected_name=$(basename "$name" | tr . _)
#
# If nothing is selected from FZF pop up, exit
if [[ -z $selected ]]; then
    exit 0
fi


dir_selected=$(ssh $selected find ~/ -mindepth 0 -maxdepth 4 -type d | fzf)

# If nothing is selected from FZF pop up, exit
if [[ -z $dir_selected ]]; then
    exit 0
fi



while :
do
echo "Press 'q' to exit"
read -p "Open in split,new session or pop up?  [sp/s/p]  " answer2

    case $answer2 in
      sp)
        tmux split-window "nvim -c \":Lexplore scp://$selected/$dir_selected/\""
        exit 0
        ;;

      s)
        tmux new-session -ds lexplore_$selected_name "nvim -c \":Lexplore scp://$selected/$dir_selected/\""
        tmux switch-client -t lexplore_$selected_name
        exit 0
        ;;
      q)
        echo "quiting"
        exit 0
        ;;

      p)
        tmux -c "tmux new-session -As lexplore_$selected_name nvim -c \":Lexplore scp://$selected/$dir_selected/\""
        exit 0
        ;;
      *)
        echo "quiting"
        exit 0
        ;;
  esac

done



