#!/usr/bin/env bash
chose=$(cat ~/.config/ssh/list.txt | fzf)
selected=$(echo $chose | awk '{print $1}')
name=$(echo $chose | awk '{print $3}')
selected_name=$(basename "$name" | tr . _)
#
# If nothing is select from FZF pop up, exit

if [[ -z $selected ]]; then
    exit 0
fi
      tmux split-window ssh -Y $selected
