#!/usr/bin/env bash

while :
do
echo "Press 'q' to exit"
read -p "Type subnet to calc: " answer
  case $answer in
    q)
      echo "quiting"
      exit 0
      ;;

    *)
    sipcalc $answer
      ;;
  esac

done

